ALTER TABLE job_payments
ADD COLUMN IF NOT EXISTS voucher_no VARCHAR(50),
ADD COLUMN IF NOT EXISTS payment_mode VARCHAR(50),
ADD COLUMN IF NOT EXISTS comments TEXT,
ADD COLUMN IF NOT EXISTS processed_by UUID REFERENCES users(id),
ADD COLUMN IF NOT EXISTS paid_at TIMESTAMP;
