
-- Migration to add fields for detailed Excel import in shipments
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS invoice_no VARCHAR(100);
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS invoice_items TEXT;
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS customs_r_form VARCHAR(100);
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS bl_awb_no VARCHAR(100);
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS container_no VARCHAR(100);
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS container_type VARCHAR(50);
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS cbm NUMERIC(10, 3);
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS no_of_pkgs VARCHAR(50);
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS expense_macl NUMERIC(15, 2) DEFAULT 0;
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS expense_mpl NUMERIC(15, 2) DEFAULT 0;
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS expense_mcs NUMERIC(15, 2) DEFAULT 0;
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS expense_transportation NUMERIC(15, 2) DEFAULT 0;
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS expense_liner NUMERIC(15, 2) DEFAULT 0;
