ALTER TABLE shipments ADD COLUMN IF NOT EXISTS house_bl VARCHAR(100);
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS vessel VARCHAR(100);
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS delivery_agent VARCHAR(255);
